# Generated by Django 2.0.7 on 2018-08-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='pic_folder/default.jpg', upload_to='pic_folder'),
        ),
    ]
