# Generated by Django 2.0.7 on 2018-08-17 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='jobproposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_proposal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobproposal',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_proposal', to='jobs.Job'),
        ),
    ]
